name: "Test"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['stable', 'oldstable']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Tidy
        run: go mod tidy && git diff --exit-code

      - name: Download
        run: go mod download

      - name: Verify
        run: go mod verify

      - name: Format
        run: gofmt -s -w . && git diff --exit-code

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -o /dev/null ./cmd/...

      - name: Test
        run: go test -v -count=1 -shuffle=on ./...
